module.exports = {
  login: require('./login'),
  register: require('./register'),
  listArticle: require('./listArticle'),
  listSort: require('./listSort'),
  saveUpFile: require('./saveUpFile'),
  listUpFile: require('./listUpFile'),
  delFile: require('./delFile'),
  retrieve: require('./retrieve'),
  findPassword: require('./findPassword'),
  active: require('./active'),
  changePassword: require('./changePassword'),
  updateArticle: require('./updateArticle'),
  passedArticle: require('./passedArticle'),
  deleteArticle: require('./deleteArticle'),
  getArticleById: require('./getArticleById'),
  updateSort: require('./updateSort'),
  deleteSort: require('./deleteSort'),
  batchDelSort: require('./batchDelSort'),
  listUser: require('./listUser'),
  passedUser: require('./passedUser'),
  deleteUser: require('./deleteUser'),
  getUserById: require('./getUserById'),
  upUserPic: require('./upUserPic'),
  updateUser: require('./updateUser')
}
